#pragma once

static const char MILESTONE_V5_SYNC_PAGE[] PROGMEM = R"HTML(
<!doctype html><html lang="ko"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>MILESTONE Sync Media</title><style>
:root{color-scheme:dark;--bg:#0b0f10;--card:#141a1c;--line:#263236;--mint:#57efc4;--text:#edf7f4;--muted:#9aaba6;--bad:#ff6b78}
*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--text);font:15px system-ui,-apple-system,"Noto Sans KR",sans-serif}main{width:min(720px,100%);margin:auto;padding:20px 14px 60px}h1{font-size:24px;margin:4px 0}h2{font-size:17px;margin:0 0 12px}.brand{color:var(--mint);letter-spacing:.08em}.sub,small{color:var(--muted)}.card{background:var(--card);border:1px solid var(--line);border-radius:14px;padding:16px;margin:14px 0}.grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.full{grid-column:1/-1}label{display:block;color:var(--muted);font-size:13px}input,select,button{width:100%;border:1px solid var(--line);border-radius:9px;padding:11px;background:#0d1214;color:var(--text);font:inherit}button{cursor:pointer}button.primary{background:var(--mint);color:#062019;border-color:var(--mint);font-weight:700}button.danger{border-color:var(--bad);color:var(--bad)}button:disabled{opacity:.45;cursor:not-allowed}.status{white-space:pre-wrap;border:1px solid var(--line);border-radius:9px;padding:11px;color:var(--muted)}.status.bad{border-color:var(--bad);color:var(--bad)}.progress{height:10px;background:#081012;border-radius:99px;overflow:hidden}.progress i{display:block;width:0;height:100%;background:var(--mint)}video{width:100%;max-height:240px;background:#000;border-radius:9px}.row{display:flex;gap:9px}.row>*{flex:1}@media(max-width:560px){.grid{grid-template-columns:1fr}.full{grid-column:1}.row{flex-direction:column}}</style></head>
<body><main><div class="brand">MILESTONE</div><h1>오디오 동기화 MEDIA</h1><p class="sub">영상은 먼저 microSD에 전부 저장하고, 오디오는 이 브라우저가 재생합니다.</p>
<section class="card"><h2>1. 원본과 변환 설정</h2><div class="grid">
<div class="full"><label>원본 동영상</label><input id="file" type="file" accept="video/*"></div>
<div><label>프레임률</label><select id="fps"><option>10</option><option selected>15</option><option>24</option><option>30</option></select></div>
<div><label>JPEG 품질</label><select id="quality"><option value="0.65">용량 절약</option><option value="0.75" selected>균형</option><option value="0.85">고화질</option></select></div>
<div class="full"><button id="convert" class="primary">전체 변환</button></div>
<div id="progress" class="full progress"><i></i></div><div id="convert_status" class="full status">원본을 선택하세요. 휴대폰 메모리 안전을 위해 변환본은 256 MiB로 제한됩니다.</div>
</div></section>
<section class="card"><h2>2. microSD 임시 저장</h2><button id="upload" class="primary" disabled>변환본 업로드</button><div id="device_status" class="status" style="margin-top:10px">기기 상태를 확인하는 중…</div></section>
<section class="card"><h2>3. 동기화 재생</h2><video id="audio" playsinline controls></video><div class="row" style="margin-top:10px"><button id="play" class="primary" disabled>동기화 재생</button><button id="pause" disabled>일시정지</button><button id="remove" class="danger">세션 삭제</button></div><p><small>브라우저를 화면에 둔 상태로 사용하세요. 화면 잠금이나 다른 앱 전환으로 오디오와 동기화 신호가 중단될 수 있습니다. 기기의 BACK을 누르면 AP와 세션이 함께 종료됩니다.</small></p></section>
<div class="row"><button onclick="location.href='/'">설정으로 돌아가기</button><button id="close">AP 종료</button></div>
</main><script>
const $=id=>document.getElementById(id),BROWSER_LIMIT=256*1024*1024;let file=null,url='',mvj=null,poll=0,syncTimer=0,busy=false,sessionReady=false,ws=null,wsWasOpen=false,eventReady=false,lastDeviceEvent=0,controlSeq=0,wsRetryAt=0;const pendingControls=new Map();
function status(id,text,bad=false){const e=$(id);e.textContent=text;e.className='status'+(bad?' bad':'')}
function le32(value){const b=new Uint8Array(4);new DataView(b.buffer).setUint32(0,value,true);return b}
function crc32(bytes){let c=0xffffffff;for(const x of bytes){c^=x;for(let i=0;i<8;i++)c=(c>>>1)^((c&1)?0xedb88320:0)}return(c^0xffffffff)>>>0}
function waitEvent(target,names,timeout){return new Promise((resolve,reject)=>{let timer;const done=()=>{clean();resolve()},fail=()=>{clean();reject(new Error('브라우저가 영상 프레임을 읽지 못했습니다.'))},clean=()=>{clearTimeout(timer);for(const n of names)target.removeEventListener(n,done);target.removeEventListener('error',fail)};for(const n of names)target.addEventListener(n,done,{once:true});target.addEventListener('error',fail,{once:true});timer=setTimeout(fail,timeout)})}
async function seek(video,time){const target=Math.max(0,Math.min(video.duration-.02,time));if(Math.abs(video.currentTime-target)<.002&&video.readyState>=2)return;const ready=waitEvent(video,['seeked','loadeddata'],12000);video.currentTime=target;await ready}
function jpeg(canvas,quality){return new Promise((resolve,reject)=>canvas.toBlob(async blob=>{if(!blob)return reject(new Error('JPEG 변환 실패'));resolve(new Uint8Array(await blob.arrayBuffer()))},'image/jpeg',quality))}
async function prepareSource(selected){if(url)URL.revokeObjectURL(url);url=URL.createObjectURL(selected);const video=$('audio');video.pause();video.muted=true;video.src=url;video.load();await waitEvent(video,['loadedmetadata'],45000);if(!Number.isFinite(video.duration)||video.duration<=0||!video.videoWidth||!video.videoHeight)throw new Error('영상 정보를 읽지 못했습니다.');return video}
$('file').addEventListener('change',async()=>{file=$('file').files[0]||null;mvj=null;$('upload').disabled=true;if(!file)return;try{const v=await prepareSource(file);status('convert_status',`${file.name}\n${v.videoWidth}×${v.videoHeight} · ${v.duration.toFixed(1)}초`)}catch(e){status('convert_status',e.message,true)}});
$('convert').onclick=async()=>{if(!file||busy)return status('convert_status','원본 동영상을 선택하세요.',true);busy=true;$('convert').disabled=true;$('upload').disabled=true;try{const video=await prepareSource(file),fps=Number($('fps').value),quality=Number($('quality').value),duration=Math.min(video.duration,3600),count=Math.ceil(duration*fps);if(count<1||count>108000)throw new Error('영상은 최대 1시간·108,000프레임까지 변환할 수 있습니다.');const canvas=document.createElement('canvas');canvas.width=canvas.height=128;const ctx=canvas.getContext('2d',{alpha:false}),parts=[],header=new Uint8Array(16),view=new DataView(header.buffer);header.set([77,86,74,49]);view.setUint16(4,128,true);view.setUint16(6,128,true);view.setUint16(8,fps,true);view.setUint16(10,0,true);view.setUint32(12,count,true);parts.push(header);let bytes=16;for(let i=0;i<count;i++){await seek(video,i/fps);ctx.fillStyle='#000';ctx.fillRect(0,0,128,128);const scale=Math.min(128/video.videoWidth,128/video.videoHeight),w=video.videoWidth*scale,h=video.videoHeight*scale;ctx.drawImage(video,(128-w)/2,(128-h)/2,w,h);const frame=await jpeg(canvas,quality);if(frame.length<4||frame.length>32768)throw new Error(`${i+1}번 JPEG 프레임 크기가 제한을 벗어났습니다.`);const record=new Uint8Array(8),rv=new DataView(record.buffer);rv.setUint32(0,frame.length,true);rv.setUint32(4,crc32(frame),true);parts.push(record,frame);bytes+=8+frame.length;if(bytes>BROWSER_LIMIT)throw new Error('변환본이 휴대폰 메모리 안전 제한 256 MiB를 넘었습니다. FPS나 JPEG 품질을 낮춰 다시 변환하세요.');$('progress').firstElementChild.style.width=Math.round((i+1)*100/count)+'%';status('convert_status',`전체 변환 중 ${i+1}/${count}\n${(bytes/1048576).toFixed(1)} MiB`);if((i&3)===3)await new Promise(r=>setTimeout(r,0))}mvj=new Blob(parts,{type:'application/octet-stream'});video.currentTime=0;video.muted=false;status('convert_status',`변환 완료 · ${count}프레임 · ${(mvj.size/1048576).toFixed(1)} MiB`);$('upload').disabled=false}catch(e){mvj=null;status('convert_status',e.message||String(e),true);$('progress').firstElementChild.style.width='0'}finally{busy=false;$('convert').disabled=false}};
$('upload').onclick=async()=>{if(!mvj||busy)return;$('audio').pause();sessionReady=false;busy=true;$('upload').disabled=true;$('play').disabled=true;$('pause').disabled=true;const chunkSize=64*1024;let offset=0;status('device_status','microSD에 임시 저장 준비 중…');try{while(offset<mvj.size){const end=Math.min(mvj.size,offset+chunkSize),final=end===mvj.size?1:0;let advanced=false,lastError=null;for(let attempt=0;attempt<3&&!advanced;attempt++){try{const body=new FormData();body.append('file',mvj.slice(offset,end),'sync.part');const response=await fetch(`/api/sync/upload?total=${mvj.size}&offset=${offset}&final=${final}`,{method:'POST',body});const result=await response.json();if(!response.ok)throw new Error(result.error||'업로드 실패');offset=end;advanced=true}catch(e){lastError=e;await new Promise(r=>setTimeout(r,400));try{const s=await api('/api/sync/status');if(s.state==='uploading'&&s.written_bytes>=end){offset=s.written_bytes;advanced=true}else if(final&&['indexing','ready'].includes(s.state)){offset=mvj.size;advanced=true}}catch{}}}if(!advanced)throw lastError||new Error('업로드 연결이 끊겼습니다.');status('device_status',`microSD에 임시 저장 중… ${Math.round(offset*100/mvj.size)}%\n${(offset/1048576).toFixed(1)} / ${(mvj.size/1048576).toFixed(1)} MiB`);await new Promise(r=>setTimeout(r,0))}status('device_status','업로드 완료 · 프레임 인덱스 검증 중…');startPoll()}catch(e){status('device_status',e.message||'업로드에 실패했습니다.',true);$('upload').disabled=false}finally{busy=false}};
async function api(path,body){const response=await fetch(path,{method:body?'POST':'GET',headers:body?{'Content-Type':'application/x-www-form-urlencoded'}:{},body:body?new URLSearchParams(body):undefined});const result=await response.json();if(!response.ok)throw new Error(result.error||`HTTP ${response.status}`);return result}
async function loadStatus(){try{const s=await api('/api/sync/status'),playback=['playing','paused'].includes(s.state)?`\n제어 ${s.control_count||0} · 요청 프레임 ${s.requested_frame} · 표시 프레임 ${s.displayed_frame} · 출력 ${s.rendered_frames||0}`:'';status('device_status',`${s.state} · ${s.indexed_frames}/${s.frames}프레임 · ${(s.written_bytes/1048576).toFixed(1)} MiB${playback}${s.error?'\n'+s.error:''}`,s.state==='error');sessionReady=['ready','playing','paused'].includes(s.state);$('play').disabled=!sessionReady;$('pause').disabled=!sessionReady;if(sessionReady&&poll){clearInterval(poll);poll=0}}catch(e){status('device_status',e.message,true)}}
function startPoll(){if(!poll)poll=setInterval(loadStatus,750);loadStatus()}
function rejectPendingControls(message){for(const pending of pendingControls.values()){clearTimeout(pending.timer);pending.reject(new Error(message))}pendingControls.clear()}function connectSocket(){try{ws=new WebSocket(`ws://${location.hostname}:81/sync-ws`);ws.binaryType='arraybuffer';ws.onopen=()=>{wsWasOpen=true;wsRetryAt=0;status('device_status','동기화 제어 연결 완료')};ws.onmessage=event=>{if(!(event.data instanceof ArrayBuffer)||(event.data.byteLength!==14&&event.data.byteLength!==16))return;const b=new Uint8Array(event.data);if(b[0]!==77||b[1]!==83||b[2]!==65||b[3]!==49)return;if(b.length===16){const pending=pendingControls.get(b[14]);if(pending){clearTimeout(pending.timer);pendingControls.delete(b[14]);b[15]===1?pending.resolve():pending.reject(new Error('기기가 동기화 제어를 거부했습니다.'))}}const deviceReady=b[12]>=3&&b[12]<=5;sessionReady=deviceReady;$('play').disabled=!deviceReady;$('pause').disabled=!deviceReady;if(!deviceReady&&!$('audio').paused){$('audio').pause();status('device_status','기기의 동기화 세션이 종료되어 오디오를 정지했습니다.',true)}const sequence=b[13];if(!eventReady){eventReady=true;lastDeviceEvent=sequence}else if(sequence!==lastDeviceEvent){lastDeviceEvent=sequence;if($('audio').paused)$('audio').play().catch(e=>status('device_status','브라우저 재생 승인이 필요합니다: '+e.message,true));else $('audio').pause()}};ws.onclose=()=>{rejectPendingControls('WebSocket 연결 종료');ws=null;if(wsWasOpen&&!$('audio').paused){$('audio').pause();status('device_status','동기화 연결이 끊겨 오디오를 정지했습니다.',true)}setTimeout(connectSocket,1200)};ws.onerror=()=>{}}catch(e){setTimeout(connectSocket,1200)}}
function sendWsControl(position,run){return new Promise((resolve,reject)=>{if(!ws||ws.readyState!==WebSocket.OPEN)return reject(new Error('WebSocket 미연결'));controlSeq=(controlSeq+1)&255;const sequence=controlSeq,data=new ArrayBuffer(10),b=new Uint8Array(data),v=new DataView(data);b.set([77,83,67,49]);v.setUint32(4,position,true);b[8]=run?1:0;b[9]=sequence;const pending={resolve,reject,timer:0};pending.timer=setTimeout(()=>{if(pendingControls.get(sequence)===pending){pendingControls.delete(sequence);reject(new Error('WebSocket ACK 시간 초과'))}},700);pendingControls.set(sequence,pending);try{ws.send(data)}catch(e){clearTimeout(pending.timer);pendingControls.delete(sequence);reject(e)}})}async function sendSync(run){const video=$('audio'),position=Math.max(0,Math.round(video.currentTime*1000));try{if(ws&&ws.readyState===WebSocket.OPEN&&Date.now()>=wsRetryAt){try{await sendWsControl(position,run);return}catch(e){wsRetryAt=Date.now()+5000}}await api('/api/sync/control',{position,running:run?1:0})}catch(e){if(sessionReady){status('device_status',e.message,true);video.pause();clearInterval(syncTimer);syncTimer=0}}}
function beginSyncLoop(){if(!sessionReady)return;sendSync(true);clearInterval(syncTimer);syncTimer=setInterval(()=>sendSync(!$('audio').paused&&!$('audio').ended),250)}
$('play').onclick=async()=>{try{await $('audio').play()}catch(e){status('device_status','오디오 재생 시작 실패: '+e.message,true)}};
$('pause').onclick=()=>{$('audio').pause()};
$('audio').addEventListener('play',beginSyncLoop);$('audio').addEventListener('pause',()=>{if(sessionReady)sendSync(false);clearInterval(syncTimer);syncTimer=0});$('audio').addEventListener('seeking',()=>{if(sessionReady)sendSync(false)});$('audio').addEventListener('seeked',()=>{if(sessionReady)sendSync(!$('audio').paused)});$('audio').addEventListener('ended',()=>sendSync(false));
$('remove').onclick=async()=>{if(!confirm('임시 영상과 동기화 세션을 삭제할까요?'))return;$('audio').pause();clearInterval(syncTimer);syncTimer=0;try{await api('/api/sync/remove',{});mvj=null;$('play').disabled=true;$('pause').disabled=true;status('device_status','세션을 삭제했습니다.')}catch(e){status('device_status',e.message,true)}};
$('close').onclick=async()=>{try{await api('/api/portal/close',{});status('device_status','AP를 종료합니다.')}catch(e){status('device_status',e.message,true)}};
setInterval(()=>{if(busy)loadStatus()},5000);connectSocket();startPoll();
</script></body></html>
)HTML";
