#pragma once

// One source tree produces two independently installable OTA applications.
// Arduino IDE builds remain backward-compatible by defaulting to CORE.
#define MILESTONE_PROFILE_CORE 1
#define MILESTONE_PROFILE_MEDIA 2

#ifndef MILESTONE_BUILD_PROFILE
#define MILESTONE_BUILD_PROFILE MILESTONE_PROFILE_CORE
#endif

#if MILESTONE_BUILD_PROFILE == MILESTONE_PROFILE_CORE
#define MILESTONE_FIRMWARE_PROFILE "core"
#define MILESTONE_FIRMWARE_PROFILE_LABEL "CORE"
#define MILESTONE_FIRMWARE_ASSET "MILESTONE_Core.bin"
#define MILESTONE_MANIFEST_ASSET "MILESTONE_Core.json"
#define MILESTONE_HAS_BLUETOOTH 1
#define MILESTONE_HAS_MEDIA 0
#define MILESTONE_PROFILE_MARKER "MILESTONE_PROFILE_CORE"
#elif MILESTONE_BUILD_PROFILE == MILESTONE_PROFILE_MEDIA
#define MILESTONE_FIRMWARE_PROFILE "media"
#define MILESTONE_FIRMWARE_PROFILE_LABEL "MEDIA"
#define MILESTONE_FIRMWARE_ASSET "MILESTONE_Media.bin"
#define MILESTONE_MANIFEST_ASSET "MILESTONE_Media.json"
#define MILESTONE_HAS_BLUETOOTH 0
#define MILESTONE_HAS_MEDIA 1
#define MILESTONE_PROFILE_MARKER "MILESTONE_PROFILE_MEDIA"
#else
#error "MILESTONE_BUILD_PROFILE must be MILESTONE_PROFILE_CORE or MILESTONE_PROFILE_MEDIA"
#endif

