#pragma once

// MILESTONE Setup portal. Kept in flash to preserve RAM.
static const char MILESTONE_PORTAL_HTML[] PROGMEM = R"HTML(
<!doctype html><html lang="ko"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>MILESTONE Setup</title>
<style>
:root{color-scheme:dark;--bg:#0b0f10;--card:#141a1c;--line:#263236;--mint:#57efc4;--text:#edf7f4;--muted:#9aaba6;--bad:#ff6b78}
*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--text);font:15px system-ui,-apple-system,"Noto Sans KR",sans-serif}
main{width:min(760px,100%);margin:auto;padding:20px 14px 60px}h1{font-size:24px;margin:4px 0}h2{font-size:17px;margin:0 0 14px}.brand{color:var(--mint);letter-spacing:.08em}.sub{color:var(--muted);margin:5px 0 18px}
.card{background:var(--card);border:1px solid var(--line);border-radius:14px;padding:16px;margin:12px 0}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.full{grid-column:1/-1}
label{display:block;color:var(--muted);font-size:13px;margin:0 0 5px}input,select,textarea,button{width:100%;border:1px solid var(--line);border-radius:9px;background:#0d1315;color:var(--text);padding:11px;font:inherit}textarea{min-height:74px;resize:vertical}
button{cursor:pointer;background:#1b2828;font-weight:700}button.primary{background:var(--mint);color:#062019;border-color:var(--mint)}button.danger{border-color:#80343d;color:#ff9da5}button:disabled{cursor:not-allowed;opacity:.48;background:#11181a;color:var(--muted);border-color:var(--line)}button.primary:disabled{background:#20302d;color:#789088;border-color:#30453f}button.install-armed{background:#2b2412;color:#f4c95d;border-color:#f4c95d}.row{display:flex;gap:9px;align-items:center}.row>*{flex:1}.check{display:flex;gap:8px;align-items:center;color:var(--text);margin:8px 0}.check input{width:auto}.status{white-space:pre-wrap;background:#0a0e0f;padding:11px;border-radius:9px;color:var(--muted);min-height:42px}.ok{color:var(--mint)}.bad{color:var(--bad)}small{color:var(--muted)}
.range-row{display:grid;grid-template-columns:minmax(0,1fr) 82px;gap:9px;align-items:center}.range-row input[type=number]{text-align:center}.saved-list{display:grid;gap:8px}.saved-entry{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:9px;align-items:center;background:#0d1315;border:1px solid var(--line);border-radius:9px;padding:9px 10px}.saved-entry button{width:auto;padding:7px 10px}.saved-name{overflow-wrap:anywhere}.badge{color:var(--mint);font-size:12px;margin-left:7px}
.media-work{display:grid;grid-template-columns:256px minmax(0,1fr);gap:14px}.media-preview{width:256px;height:256px;image-rendering:pixelated;background:#000;border:1px solid var(--line);border-radius:9px}.media-list{display:grid;gap:8px;margin-top:12px}.media-entry{display:grid;grid-template-columns:minmax(110px,1fr) 76px auto;gap:7px;align-items:center;background:#0d1315;border:1px solid var(--line);border-radius:9px;padding:9px}.media-entry input{padding:8px}.media-actions{display:flex;gap:5px}.media-actions button{width:auto;padding:7px 9px}.media-meta{grid-column:1/-1;color:var(--muted);font-size:12px}.progress{height:8px;background:#0a0e0f;border-radius:8px;overflow:hidden}.progress>i{display:block;height:100%;width:0;background:var(--mint)}
@media(max-width:560px){.grid{grid-template-columns:1fr}.row{flex-direction:column}.row>*{width:100%}}
@media(max-width:620px){.media-work{grid-template-columns:1fr}.media-preview{width:min(256px,100%);height:auto;aspect-ratio:1}}
</style></head><body><main>
<div class="brand">CYTRON//MILESTONE</div><h1>MILESTONE Setup</h1><p class="sub">MILESTONE D1 로컬 설정 포털</p>

<section class="card"><h2>상태</h2><div id="status" class="status">상태를 불러오는 중…</div><div class="row" style="margin-top:10px"><button onclick="syncTime()">지금 시간 동기화</button><button onclick="exportConfig()">설정 JSON 보기</button></div><textarea id="export" class="full" hidden readonly></textarea></section>

<section class="card"><h2>진단</h2><div id="diagnostics" class="status">진단 정보를 불러오는 중…</div><div class="row" style="margin-top:10px"><button onclick="copyDiagnostics()">진단 정보 복사</button><button class="danger" onclick="clearDiagnostics()">진단 이력 지우기</button></div><p><small>최근 16개의 부팅·네트워크·NTP·OTA·롤백·온도·미디어 오류 이벤트만 저장합니다. 일반 화면 전환이나 RSSI 변화는 기록하지 않습니다.</small></p></section>

<section class="card"><h2>펌웨어 업데이트</h2><div id="update_status" class="status">업데이트 상태를 불러오는 중…</div><div class="row" style="margin-top:10px"><button onclick="checkUpdate()">지금 업데이트 확인</button><button id="install_update" class="primary" onclick="installUpdate()" disabled>업데이트 설치</button></div><p><small>GitHub의 CXITRON/MILESTONE-Core 최신 정식 Release를 확인합니다. 설치 중에는 전원을 분리하지 마세요.</small></p></section>

<section class="card"><h2>네트워크</h2><div class="grid">
<div class="full row"><select id="scan"><option value="">주변 Wi-Fi 검색 전</option></select><button onclick="scanWifi()">검색</button></div>
<div><label>Wi-Fi 보안 방식</label><select id="wifi_security" onchange="syncWifiSecurityUi()"><option value="personal">Personal / Open</option><option value="enterprise_peap">WPA2-Enterprise (PEAP)</option></select></div>
<div><label>Wi-Fi SSID</label><input id="ssid" maxlength="32" autocomplete="off"></div>
<div id="enterprise_username_row" hidden><label>Enterprise 사용자명</label><input id="wifi_username" maxlength="64" autocomplete="username" placeholder="학교 계정 ID"></div>
<div id="enterprise_identity_row" hidden><label>Enterprise identity (선택)</label><input id="wifi_identity" maxlength="64" autocomplete="off" placeholder="비우면 사용자명 사용"></div>
<div class="full"><label id="pass_label">Wi-Fi 비밀번호</label><input id="pass" type="password" maxlength="64" autocomplete="new-password" placeholder="저장된 비밀번호는 표시하지 않음"></div>
<div id="enterprise_help" class="full" hidden><small>현재 펌웨어는 WPA2-Enterprise의 사용자명·비밀번호 기반 PEAP를 지원합니다. identity를 비우면 사용자명을 사용합니다. WPA3-Enterprise, 인증서 기반 EAP-TLS 또는 학교 CA 인증서가 필수인 환경은 현재 지원하지 않습니다.</small></div>
<div class="full"><button class="primary" onclick="testWifi()">Wi-Fi 시험 후 확정 저장</button></div>
<div class="full"><label>저장된 Wi-Fi (최근 성공 순, 최대 8개)</label><div id="saved_networks" class="saved-list"><small>저장된 네트워크를 불러오는 중…</small></div></div>
</div></section>

<section class="card"><h2>디데이와 문구</h2><div class="grid">
<div><label>목표 이름 (24자 이내)</label><input id="title" maxlength="24"></div>
<div><label>목표 날짜</label><input id="target" type="date"></div>
<div><label>디데이 계산 주기</label><select id="dday_period"><option value="0">매일 자정</option><option value="60">매분</option><option value="600">10분</option><option value="1800">30분</option><option value="3600">1시간</option></select></div>
<div class="full"><label>문구 (60자 이내)</label><textarea id="message" maxlength="60"></textarea></div>
<div><label>디데이 표기</label><select id="dday_style"><option value="0">D-N</option><option value="1">N일 남음</option></select></div>
<div><label>목표일 이후</label><select id="after_mode"><option value="0">D+N</option><option value="1">디데이 표시 종료</option></select></div>
<div><label>문구 정렬</label><select id="msg_align"><option value="0">가운데</option><option value="1">왼쪽</option></select></div>
<div><label>스크롤 속도(px/s)</label><input id="scroll_speed" type="number" min="5" max="80"></div>
<label class="check full"><input id="msg_scroll" type="checkbox"> 긴 문구 자동 스크롤</label>
</div></section>

<section class="card"><h2>표시 모드</h2><div class="grid">
<div class="full"><label>기본 모드</label><select id="mode"><option value="0">디데이(시간)</option><option value="1">디데이(문구)</option><option value="2">문구 단독</option><option value="3">시간 단독</option><option value="4">문구 + 시간</option><option value="5">종합 화면</option><option value="7">기기 세부정보</option><option value="8">커스텀 미디어</option><option value="6">선택 순환</option></select></div>
<div class="full"><label>순환 포함 화면</label>
<label class="check"><input class="cycle" value="0" type="checkbox"> 디데이(시간)</label><label class="check"><input class="cycle" value="1" type="checkbox"> 디데이(문구)</label><label class="check"><input class="cycle" value="2" type="checkbox"> 문구 단독</label><label class="check"><input class="cycle" value="3" type="checkbox"> 시간 단독</label><label class="check"><input class="cycle" value="4" type="checkbox"> 문구 + 시간</label><label class="check"><input class="cycle" value="5" type="checkbox"> 종합 화면</label><label class="check"><input class="cycle" value="6" type="checkbox"> 기기 세부정보</label><label class="check"><input class="cycle" value="7" type="checkbox"> 커스텀 미디어</label></div>
<div><label>순환 순서 (0~7)</label><input id="cycle_order" maxlength="15" placeholder="0,1,2,3,4,5,6,7"></div>
<div><label>자동 전환(초, 0 또는 3~60)</label><input id="cycle_interval" type="number" min="0" max="60"></div>
</div></section>

<section class="card"><h2>시간과 화면</h2><div class="grid">
<div><label>시간 형식</label><select id="hour24"><option value="1">24시간제</option><option value="0">12시간제</option></select></div>
<div><label>초 표시</label><select id="show_seconds"><option value="0">끄기</option><option value="1">켜기</option></select></div>
<label class="check full"><input id="show_temp" type="checkbox"> 상단 상태 기호 옆에 ESP32 칩 온도 표시</label>
<div class="full"><small>칩 내부 온도이므로 주변 실내 온도보다 높게 표시될 수 있습니다. 이 토글은 평상시 표시만 제어하며 과열 경고와 보호 기능은 항상 작동합니다.</small></div>
<div><label>NTP 동기화 주기</label><select id="ntp_period"><option value="3600">1시간</option><option value="10800">3시간</option><option value="21600">6시간</option><option value="43200">12시간</option><option value="86400">24시간</option><option value="0">수동</option></select></div>
<div><label>Wi-Fi 재시도 주기</label><select id="retry_period"><option value="60">1분</option><option value="300">5분</option><option value="900">15분</option><option value="1800">30분</option></select></div>
<label class="check"><input id="boot_sync" type="checkbox"> 부팅 직후 시간 동기화</label><label class="check"><input id="wifi_sleep" type="checkbox"> 동기화 뒤 Wi-Fi 끄기</label><label class="check"><input id="burnin" type="checkbox"> 번인 방지 ±1px 이동</label>
<div><label>일반 밝기 (1~255)</label><div class="range-row"><input id="brightness" type="range" min="1" max="255"><input id="brightness_num" type="number" min="1" max="255" aria-label="일반 밝기 값"></div></div>
<div><label>야간 밝기 (1~255)</label><div class="range-row"><input id="night_level" type="range" min="1" max="255"><input id="night_level_num" type="number" min="1" max="255" aria-label="야간 밝기 값"></div></div>
<label class="check full"><input id="led_enabled" type="checkbox"> RGB 상태 LED 계속 표시</label>
<div><label>상태 LED 밝기 (1~64)</label><div class="range-row"><input id="led_brightness" type="range" min="1" max="64"><input id="led_brightness_num" type="number" min="1" max="64" aria-label="상태 LED 밝기 값"></div></div>
<div><label>야간 LED 밝기 (1~32)</label><div class="range-row"><input id="led_night_level" type="range" min="1" max="32"><input id="led_night_level_num" type="number" min="1" max="32" aria-label="야간 LED 밝기 값"></div></div>
<div><label>야간 시작</label><input id="night_start" type="time"></div><div><label>야간 종료</label><input id="night_end" type="time"></div>
<div><label>정지 화면 자동 끄기(분, 0=사용 안 함)</label><input id="screen_off" type="number" min="0" max="1440"></div>
</div></section>

<section class="card"><h2>커스텀 미디어</h2>
<div class="media-work"><canvas id="media_preview" class="media-preview" width="128" height="128"></canvas><div class="grid">
<div class="full"><label>사진·GIF·영상 파일</label><input id="media_file" type="file" accept="image/*,video/*"></div>
<div><label>이름 (12자)</label><input id="media_name" maxlength="12"></div><div><label>항목 표시시간</label><input id="media_display" type="number" min="3" max="60" value="8"></div>
<div><label>맞춤</label><select id="media_fit"><option value="cover">화면 채우기</option><option value="contain">전체 보이기</option></select></div><div><label>흑백 변환</label><select id="media_dither"><option value="bayer">Bayer 디더링</option><option value="floyd">Floyd–Steinberg</option><option value="threshold">단순 임계값</option></select></div>
<div><label>밝기 (-100~100)</label><input id="media_brightness" type="number" min="-100" max="100" value="0"></div><div><label>대비 (-100~100)</label><input id="media_contrast" type="number" min="-100" max="100" value="0"></div>
<div><label>밝기 임계값</label><input id="media_threshold" type="range" min="40" max="220" value="128"></div><div><label>투명 여백</label><select id="media_background"><option value="black">검은색</option><option value="white">흰색</option></select></div>
<div><label>애니메이션 FPS</label><select id="media_fps"><option value="5">5 fps</option><option value="8">8 fps</option><option value="10">10 fps</option></select></div><div><label>영상 시작(초)</label><input id="media_start" type="number" min="0" max="3600" step="0.1" value="0"></div>
<div><label>최대 길이(초)</label><input id="media_duration" type="number" min="1" max="40" value="8"></div><label class="check"><input id="media_invert" type="checkbox"> 흑백 반전</label><label class="check"><input id="media_loop" type="checkbox" checked> 애니메이션 반복</label>
<div class="full"><button id="media_convert" onclick="convertMedia()">변환 및 미리보기</button></div><div class="full"><button id="media_upload" class="primary" onclick="uploadMedia()" disabled>기기에 업로드</button></div>
<div class="full progress"><i id="media_progress"></i></div><div id="media_info" class="full"><small>원본은 브라우저에서만 처리되며 기기에는 128×128 흑백 변환본만 저장됩니다.</small></div>
</div></div>
<div id="media_storage" class="status" style="margin-top:12px">미디어 저장소를 불러오는 중…</div><div id="media_list" class="media-list"></div>
<div class="row" style="margin-top:10px"><button onclick="loadMedia()">목록 새로고침</button><button class="danger" onclick="clearMedia()">미디어 전체 삭제</button><button class="danger" onclick="repairMedia()">저장소 복구</button></div>
</section>

<section class="card"><button class="primary" onclick="saveConfig()">화면·시간 설정 저장</button><p><small>Wi-Fi 비밀번호는 조회되지 않으며, Wi-Fi 시험 성공 시에만 확정 저장됩니다.</small></p></section>
<section class="card"><h2>시스템</h2><div class="grid"><div><button onclick="resetSettings()">표시 설정 기본값 복원</button><p><small>저장된 Wi-Fi는 유지하고 화면·시간·LED 설정만 초기화합니다.</small></p></div><div><button class="danger" onclick="factoryReset()">공장 초기화</button><p><small>저장된 Wi-Fi를 포함한 모든 데이터를 삭제하고 재부팅합니다.</small></p></div></div></section>
</main><script>
let wifiPolling=false,installConfirmArmed=false,installConfirmTimer=0,installRequestPending=false,convertedMedia=null,mediaPreviewTimer=0,mediaPreviewFrames=[];
const $=id=>document.getElementById(id); const val=id=>$(id).value;
function form(obj){return new URLSearchParams(obj)}
function setStatus(s,cls=''){const e=$('status');e.textContent=s;e.className='status '+cls}
async function api(url,opt={}){const r=await fetch(url,opt);const t=await r.text();let d;try{d=JSON.parse(t)}catch{d={ok:false,error:t||r.statusText}}if(!r.ok)throw new Error(d.error||('HTTP '+r.status));return d}
function minsToTime(n){n=Number(n)||0;return String(Math.floor(n/60)).padStart(2,'0')+':'+String(n%60).padStart(2,'0')}
function timeToMins(s){const a=s.split(':').map(Number);return (a[0]||0)*60+(a[1]||0)}
const rangePairs=[['brightness','brightness_num'],['night_level','night_level_num'],['led_brightness','led_brightness_num'],['led_night_level','led_night_level_num']];
function bindRangePair(rangeId,numberId){const r=$(rangeId),n=$(numberId);const clamp=v=>Math.min(Number(r.max),Math.max(Number(r.min),Number(v)||Number(r.min)));r.addEventListener('input',()=>n.value=r.value);n.addEventListener('input',()=>{n.value=clamp(n.value);r.value=n.value});n.addEventListener('change',()=>{n.value=clamp(n.value);r.value=n.value})}
function syncRangePairs(){rangePairs.forEach(([r,n])=>$(n).value=$(r).value)}
function syncWifiSecurityUi(){const enterprise=val('wifi_security')==='enterprise_peap';$('enterprise_username_row').hidden=!enterprise;$('enterprise_identity_row').hidden=!enterprise;$('enterprise_help').hidden=!enterprise;$('pass_label').textContent=enterprise?'Enterprise 비밀번호':'Wi-Fi 비밀번호';$('pass').maxLength=enterprise?64:63}
function renderSavedNetworks(networks=[]){const box=$('saved_networks');box.replaceChildren();if(!networks.length){const s=document.createElement('small');s.textContent='저장된 Wi-Fi가 없습니다.';box.appendChild(s);return}networks.forEach(n=>{const row=document.createElement('div');row.className='saved-entry';const name=document.createElement('div');name.className='saved-name';name.textContent=n.ssid;const type=document.createElement('span');type.className='badge';type.textContent=n.security==='enterprise_peap'?'Enterprise':'Personal';name.appendChild(type);if(n.preferred){const b=document.createElement('span');b.className='badge';b.textContent='최근 성공';name.appendChild(b)}const del=document.createElement('button');del.type='button';del.className='danger';del.textContent='삭제';del.onclick=()=>deleteSavedWifi(n.ssid);row.append(name,del);box.appendChild(row)})}
const diagLabels={boot:'BOOT',boot_validated:'BOOT VALIDATED',wifi_connected:'Wi-Fi CONNECTED',wifi_connect_timeout:'Wi-Fi TIMEOUT',wifi_disconnected:'Wi-Fi DISCONNECTED',wifi_test_failed:'Wi-Fi TEST FAILED',ntp_success:'NTP SUCCESS',ntp_timeout:'NTP TIMEOUT',update_check_failed:'UPDATE CHECK FAILED',ota_start:'OTA START',ota_failed:'OTA FAILED',ota_ready:'OTA READY',rollback_armed:'ROLLBACK ARMED',boot_candidate:'BOOT CANDIDATE',rollback_triggered:'ROLLBACK TRIGGERED',rollback_confirmed:'ROLLBACK CONFIRMED',thermal_warning:'THERMAL WARNING',thermal_throttle:'THERMAL THROTTLE',thermal_protection:'THERMAL PROTECTION',thermal_recovered:'THERMAL RECOVERED',temperature_sensor_fault:'TEMP SENSOR FAULT',media_failed:'MEDIA FAILED'};
function diagTime(e){return e.time||`uptime +${Number(e.uptime_sec||0)}s`}
function diagLine(e){const label=diagLabels[e.event]||e.event||'unknown';return `[${diagTime(e)}] ${label}${e.detail?' — '+e.detail:''}`}
function renderDiagnostics(d){const lines=[`마지막 부팅: ${d.last_boot||'-'}`,`부팅 상태: ${d.boot_validated?'정상 확인됨':'확인 대기/실패'}`,`마지막 정상 확인 uptime: ${d.last_validated_uptime_sec||'-'} s`,`최고 칩 온도: ${d.max_temperature_c??'-'} °C`,`최근 OTA: ${d.last_ota_result||'-'}`,`최근 롤백: ${d.rollback_last||'-'}${d.rollback_reason?' — '+d.rollback_reason:''}`,`최근 오류: ${d.last_error?((diagLabels[d.last_error.event]||d.last_error.event)+(d.last_error.detail?' — '+d.last_error.detail:'')):'없음'}`,`저장 이력: ${d.history_count||0}/16`,'',...(d.events||[]).map(diagLine)];const e=$('diagnostics');e.textContent=lines.join('\n');e.className='status '+(d.last_error?'':'ok')}
async function refreshDiagnostics(){try{renderDiagnostics(await api('/api/diagnostics'))}catch(e){const box=$('diagnostics');box.textContent=e.message;box.className='status bad'}}
function copyTextFallback(text){const t=document.createElement('textarea');t.value=text;t.style.position='fixed';t.style.opacity='0';document.body.appendChild(t);t.select();let ok=false;try{ok=document.execCommand('copy')}catch{}t.remove();return ok}
async function copyDiagnostics(){try{const [s,d]=await Promise.all([api('/api/status'),api('/api/diagnostics')]);const up=Number(s.uptime_sec||0);const uptime=`${Math.floor(up/86400)}d ${String(Math.floor(up/3600)%24).padStart(2,'0')}:${String(Math.floor(up/60)%60).padStart(2,'0')}:${String(up%60).padStart(2,'0')}`;const text=['MILESTONE Core Diagnostics',`Firmware: ${s.firmware}`,`Uptime: ${uptime}`,`Reset: ${d.last_boot||'-'}`,`Boot validated: ${d.boot_validated?'yes':'no'}`,`Wi-Fi: ${s.wifi||'-'}`,`NTP: ${s.time_valid?'synchronized':'not synchronized'}`,`Last sync: ${s.last_sync||'-'}`,`Temperature: ${s.temperature_c??'-'} C`,`Max temperature: ${d.max_temperature_c??'-'} C`,`Last OTA: ${d.last_ota_result||'-'}`,`Last rollback: ${d.rollback_last||'-'}${d.rollback_reason?' — '+d.rollback_reason:''}`,'','Recent events:',...(d.events||[]).map(diagLine)].join('\n');let ok=false;if(navigator.clipboard&&window.isSecureContext){try{await navigator.clipboard.writeText(text);ok=true}catch{}}if(!ok)ok=copyTextFallback(text);setStatus(ok?'진단 정보를 클립보드에 복사했습니다.':'복사에 실패했습니다. 진단 영역을 길게 눌러 직접 복사해 주세요.',ok?'ok':'bad')}catch(e){setStatus(e.message,'bad')}}
async function clearDiagnostics(){if(!confirm('최근 진단 이력 16개를 모두 지우시겠습니까? 설정과 Wi-Fi는 유지됩니다.'))return;try{await api('/api/diagnostics/clear',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:form({})});await refreshDiagnostics();setStatus('진단 이력을 지웠습니다.','ok')}catch(e){setStatus(e.message,'bad')}}
const mediaCanvas=$('media_preview'),mediaCtx=mediaCanvas.getContext('2d',{willReadFrequently:true}),workCanvas=document.createElement('canvas'),workCtx=workCanvas.getContext('2d',{willReadFrequently:true});workCanvas.width=workCanvas.height=128;
function mediaMessage(text,bad=false){const e=$('media_info');e.textContent=text;e.className=bad?'bad':''}
function le16(v,n){v.push(n&255,(n>>>8)&255)}function le32(v,n){v.push(n&255,(n>>>8)&255,(n>>>16)&255,(n>>>24)&255)}
function crc32(a){let c=0xffffffff;for(const b of a){c^=b;for(let i=0;i<8;i++)c=(c>>>1)^((c&1)?0xedb88320:0)}return(c^0xffffffff)>>>0}
function showPacked(frame){const image=mediaCtx.createImageData(128,128);for(let y=0;y<128;y++)for(let x=0;x<128;x++){const on=(frame[x+(y>>3)*128]&(1<<(y&7)))!==0,o=(y*128+x)*4;image.data[o]=image.data[o+1]=image.data[o+2]=on?255:0;image.data[o+3]=255}mediaCtx.putImageData(image,0,0)}
function startMediaPreview(frames){clearInterval(mediaPreviewTimer);mediaPreviewFrames=frames;let i=0;showPacked(frames[0].bits);if(frames.length>1){const step=()=>{showPacked(frames[i].bits);const delay=Math.max(100,frames[i].delay);i=(i+1)%frames.length;mediaPreviewTimer=setTimeout(step,delay)};mediaPreviewTimer=setTimeout(step,Math.max(100,frames[0].delay))}}
function drawToWork(source,width,height){workCtx.save();workCtx.setTransform(1,0,0,1,0,0);workCtx.fillStyle=val('media_background')==='white'?'#fff':'#000';workCtx.fillRect(0,0,128,128);const scale=val('media_fit')==='contain'?Math.min(128/width,128/height):Math.max(128/width,128/height),w=width*scale,h=height*scale;workCtx.imageSmoothingEnabled=true;workCtx.imageSmoothingQuality='high';workCtx.drawImage(source,(128-w)/2,(128-h)/2,w,h);workCtx.restore()}
function packWork(){const p=workCtx.getImageData(0,0,128,128).data,out=new Uint8Array(2048),threshold=Number(val('media_threshold')),brightness=Math.max(-100,Math.min(100,Number(val('media_brightness'))||0))*2.55,contrast=Math.max(-100,Math.min(100,Number(val('media_contrast'))||0)),factor=(259*(contrast+255))/(255*(259-contrast)),invert=$('media_invert').checked,bayer=[0,8,2,10,12,4,14,6,3,11,1,9,15,7,13,5],mode=val('media_dither'),gray=new Float32Array(16384);for(let i=0;i<16384;i++){const o=i*4,a=p[o+3]/255;let lum=(.2126*p[o]+.7152*p[o+1]+.0722*p[o+2])*a;lum=Math.max(0,Math.min(255,factor*(lum-128)+128+brightness));gray[i]=invert?255-lum:lum}for(let y=0;y<128;y++)for(let x=0;x<128;x++){const i=y*128+x,t=threshold+(mode==='bayer'?(bayer[(y&3)*4+(x&3)]-7.5)*8:0),on=gray[i]>=t;if(on)out[x+(y>>3)*128]|=1<<(y&7);if(mode==='floyd'){const e=gray[i]-(on?255:0);if(x<127)gray[i+1]+=e*7/16;if(y<127){if(x)gray[i+127]+=e*3/16;gray[i+128]+=e*5/16;if(x<127)gray[i+129]+=e/16}}}return out}
function deltaRle(prev,cur){const xor=new Uint8Array(2048);for(let i=0;i<2048;i++)xor[i]=prev[i]^cur[i];const out=[];for(let i=0;i<2048;){const zero=xor[i]===0;let n=1;while(n<128&&i+n<2048&&(xor[i+n]===0)===zero)n++;out.push((zero?0:128)|(n-1));if(!zero)for(let j=0;j<n;j++)out.push(xor[i+j]);i+=n}return new Uint8Array(out)}
function buildMsm(frames,loop){const payload=[];let duration=0,previous=null;frames.forEach((frame,index)=>{let encoding=0,data=frame.bits;if(index){const delta=deltaRle(previous,frame.bits);if(delta.length<2048){encoding=1;data=delta}}const delay=frames.length===1?0:Math.min(60000,Math.max(1,Math.round(frame.delay)));payload.push(encoding);le16(payload,delay);le16(payload,data.length);payload.push(...data);duration+=delay;previous=frame.bits});const body=new Uint8Array(payload);if(body.length+24>163840)throw new Error('변환 결과가 160 KiB 한도를 넘습니다. FPS나 영상 길이를 줄여 주세요.');const header=[];header.push(77,83,77,49,1,(frames.length>1?1:0)|(frames.length>1&&loop?2:0),128,128);le16(header,frames.length);le16(header,0);le32(header,duration);le32(header,body.length);le32(header,crc32(body));return new Blob([new Uint8Array(header),body],{type:'application/octet-stream'})}
function readGifBlocks(bytes,state){const chunks=[];let total=0;for(;;){const n=bytes[state.p++];if(!n)break;if(state.p+n>bytes.length)throw new Error('GIF 데이터가 잘렸습니다.');chunks.push(bytes.subarray(state.p,state.p+n));state.p+=n;total+=n}const out=new Uint8Array(total);let p=0;for(const c of chunks){out.set(c,p);p+=c.length}return out}
function gifLzw(min,data,expected){const clear=1<<min,end=clear+1;let size=min+1,next=end+1,bits=0,held=0,pos=0,dict=[];const reset=()=>{dict=[];for(let i=0;i<clear;i++)dict[i]=[i];size=min+1;next=end+1};const code=()=>{while(bits<size){if(pos>=data.length)return null;held|=data[pos++]<<bits;bits+=8}const c=held&((1<<size)-1);held>>>=size;bits-=size;return c};reset();const out=[];let prev=null;for(;;){const c=code();if(c===null||c===end)break;if(c===clear){reset();prev=null;continue}let entry;if(c<dict.length&&dict[c])entry=dict[c];else if(c===next&&prev)entry=prev.concat(prev[0]);else throw new Error('지원하지 않는 GIF LZW 스트림입니다.');out.push(...entry);if(prev){dict[next++]=prev.concat(entry[0]);if(next===(1<<size)&&size<12)size++}prev=entry;if(out.length>=expected)break}return out.slice(0,expected)}
async function decodeGif(file){const b=new Uint8Array(await file.arrayBuffer()),s={p:0};if(String.fromCharCode(...b.subarray(0,6)).slice(0,3)!=='GIF')throw new Error('GIF 헤더가 올바르지 않습니다.');s.p=6;const u16=()=>{const n=b[s.p]|(b[s.p+1]<<8);s.p+=2;return n},w=u16(),h=u16();if(!w||!h||w*h>4194304)throw new Error('GIF 해상도가 너무 큽니다.');const packed=b[s.p++];s.p+=2;const table=n=>{const t=[];for(let i=0;i<n;i++)t.push([b[s.p++],b[s.p++],b[s.p++]]);return t};const global=packed&128?table(1<<((packed&7)+1)):null,screen=new Uint8ClampedArray(w*h*4),frames=[];let gce={delay:100,trans:-1,dispose:0},prior=null;while(s.p<b.length&&frames.length<300){const marker=b[s.p++];if(marker===0x3b)break;if(marker===0x21){const label=b[s.p++];if(label===0xf9){const n=b[s.p++];if(n!==4)throw new Error('GIF 제어 블록이 올바르지 않습니다.');const f=b[s.p++],delay=u16(),trans=b[s.p++];s.p++;gce={delay:Math.max(100,delay*10),trans:f&1?trans:-1,dispose:(f>>2)&7}}else readGifBlocks(b,s);continue}if(marker!==0x2c)throw new Error('GIF 블록을 해석하지 못했습니다.');if(prior){if(prior.dispose===2){for(let y=prior.top;y<prior.top+prior.h;y++)for(let x=prior.left;x<prior.left+prior.w;x++)screen.fill(0,(y*w+x)*4,(y*w+x)*4+4)}else if(prior.dispose===3&&prior.saved)screen.set(prior.saved)}const left=u16(),top=u16(),iw=u16(),ih=u16(),ip=b[s.p++],colors=ip&128?table(1<<((ip&7)+1)):global;if(!colors||left+iw>w||top+ih>h)throw new Error('GIF 프레임 범위가 올바르지 않습니다.');const saved=gce.dispose===3?screen.slice():null,min=b[s.p++],indices=gifLzw(min,readGifBlocks(b,s),iw*ih),rows=[];if(ip&64){for(const [start,step] of [[0,8],[4,8],[2,4],[1,2]])for(let y=start;y<ih;y+=step)rows.push(y)}else for(let y=0;y<ih;y++)rows.push(y);let q=0;for(const ry of rows)for(let x=0;x<iw;x++){const ci=indices[q++];if(ci===gce.trans)continue;const c=colors[ci];if(!c)continue;const o=((top+ry)*w+left+x)*4;screen[o]=c[0];screen[o+1]=c[1];screen[o+2]=c[2];screen[o+3]=255}frames.push({image:new ImageData(screen.slice(),w,h),delay:gce.delay});prior={left,top,w:iw,h:ih,dispose:gce.dispose,saved};gce={delay:100,trans:-1,dispose:0}}if(!frames.length)throw new Error('GIF에서 표시할 프레임을 찾지 못했습니다.');return{width:w,height:h,frames}}
async function seekVideo(video,time){if(Math.abs(video.currentTime-time)<.002)return;await new Promise((resolve,reject)=>{const done=()=>{cleanup();resolve()},fail=()=>{cleanup();reject(new Error('영상 프레임을 읽지 못했습니다.'))},cleanup=()=>{video.removeEventListener('seeked',done);video.removeEventListener('error',fail)};video.addEventListener('seeked',done,{once:true});video.addEventListener('error',fail,{once:true});video.currentTime=time})}
async function loadStillImage(file){const url=URL.createObjectURL(file),image=new Image();image.decoding='async';image.src=url;try{await image.decode()}catch{await new Promise((resolve,reject)=>{image.onload=resolve;image.onerror=()=>reject(new Error('이 브라우저가 사진 형식을 읽지 못합니다.'))})}return{source:image,width:image.naturalWidth,height:image.naturalHeight,close:()=>URL.revokeObjectURL(url)}}
async function convertMedia(){const file=$('media_file').files[0];if(!file)return mediaMessage('먼저 사진, GIF 또는 영상 파일을 선택해 주세요.',true);$('media_convert').disabled=true;$('media_upload').disabled=true;convertedMedia=null;$('media_progress').style.width='0%';try{if(!$('media_name').value)$('media_name').value=file.name.replace(/\.[^.]+$/,'').slice(0,12);const maxSeconds=Math.min(40,Math.max(1,Number(val('media_duration'))||8)),startSeconds=Math.max(0,Number(val('media_start'))||0),fps=Math.min(10,Math.max(5,Number(val('media_fps'))||5)),frames=[];if(file.type==='image/gif'||/\.gif$/i.test(file.name)){mediaMessage('GIF 프레임을 해석하는 중…');const gif=await decodeGif(file),timeline=[];let total=0;for(const f of gif.frames){total+=f.delay;timeline.push(total)}const duration=Math.min(maxSeconds*1000,total),count=Math.max(1,Math.min(300,Math.ceil(duration*fps/1000)));for(let i=0,sourceIndex=0;i<count;i++){const time=i*1000/fps;while(sourceIndex+1<timeline.length&&timeline[sourceIndex]<=time)sourceIndex++;const f=gif.frames[sourceIndex],source=document.createElement('canvas');source.width=gif.width;source.height=gif.height;source.getContext('2d').putImageData(f.image,0,0);drawToWork(source,gif.width,gif.height);frames.push({bits:packWork(),delay:Math.round(1000/fps)});$('media_progress').style.width=Math.round(100*(i+1)/count)+'%'}}else if(file.type.startsWith('video/')){const url=URL.createObjectURL(file),video=document.createElement('video');video.muted=true;video.playsInline=true;video.preload='auto';video.src=url;await new Promise((resolve,reject)=>{video.onloadeddata=resolve;video.onerror=()=>reject(new Error('이 브라우저가 영상 형식을 읽지 못합니다.'))});const start=Math.min(startSeconds,Math.max(0,video.duration-.02)),duration=Math.min(maxSeconds,Math.max(.02,video.duration-start)),count=Math.max(1,Math.min(300,Math.ceil(duration*fps)));for(let i=0;i<count;i++){await seekVideo(video,Math.min(Math.max(0,video.duration-.02),start+i/fps));drawToWork(video,video.videoWidth,video.videoHeight);frames.push({bits:packWork(),delay:Math.round(1000/fps)});$('media_progress').style.width=Math.round(100*(i+1)/count)+'%'}URL.revokeObjectURL(url)}else if(file.type.startsWith('image/')){const image=await loadStillImage(file);drawToWork(image.source,image.width,image.height);frames.push({bits:packWork(),delay:0});image.close()}else throw new Error('지원하는 사진·GIF·영상 파일이 아닙니다.');if(!frames.length)throw new Error('변환할 프레임이 없습니다.');convertedMedia=buildMsm(frames,$('media_loop').checked);startMediaPreview(frames);$('media_upload').disabled=false;$('media_progress').style.width='100%';mediaMessage(`${frames.length}프레임 · ${(convertedMedia.size/1024).toFixed(1)} KiB 변환 완료`)}catch(e){mediaMessage(e.message,true);$('media_progress').style.width='0%'}finally{$('media_convert').disabled=false}}
async function uploadMedia(){if(!convertedMedia)return;const name=val('media_name').trim(),display=Number(val('media_display'));if(!name||[...name].length>12||new TextEncoder().encode(name).length>=49)return mediaMessage('이름은 12자, UTF-8 48바이트 이하여야 합니다.',true);$('media_upload').disabled=true;mediaMessage('변환본을 기기에 업로드하는 중…');try{const data=new FormData();data.append('file',convertedMedia,'media.msm');const q=new URLSearchParams({name,size:convertedMedia.size,display});const r=await fetch('/api/media/upload?'+q,{method:'POST',body:data});const t=await r.text();let d;try{d=JSON.parse(t)}catch{d={error:t}}if(!r.ok)throw new Error(d.error||'업로드에 실패했습니다.');mediaMessage(`업로드 완료 · ${d.frames}프레임 · ${(convertedMedia.size/1024).toFixed(1)} KiB`);convertedMedia=null;await loadMedia()}catch(e){mediaMessage(e.message,true);$('media_upload').disabled=false}}
function mediaButton(text,fn,cls=''){const b=document.createElement('button');b.textContent=text;b.onclick=fn;if(cls)b.className=cls;return b}
async function loadMedia(){try{const [s,l]=await Promise.all([api('/api/media/status'),api('/api/media/list')]);const free=Math.max(0,s.media_limit_bytes-s.media_used_bytes);$('media_storage').textContent=s.ready?`미디어: ${s.item_count}/${s.max_items}개 · ${(s.media_used_bytes/1024).toFixed(1)} KiB 사용 · ${(free/1024).toFixed(1)} KiB 여유${s.psram?' · PSRAM':' · 내부 RAM'}`:'미디어 저장소를 사용할 수 없습니다.';$('media_storage').className='status '+(s.ready?'ok':'bad');const box=$('media_list');box.replaceChildren();if(!l.items.length){const small=document.createElement('small');small.textContent='저장된 커스텀 미디어가 없습니다.';box.appendChild(small)}for(const item of l.items){const row=document.createElement('div');row.className='media-entry';const name=document.createElement('input');name.value=item.name;name.maxLength=12;const seconds=document.createElement('input');seconds.type='number';seconds.min=3;seconds.max=60;seconds.value=item.display_seconds;const enabled=document.createElement('label');enabled.className='check';const check=document.createElement('input');check.type='checkbox';check.checked=item.enabled;enabled.append(check,document.createTextNode('사용'));const actions=document.createElement('div');actions.className='media-actions';actions.append(mediaButton('저장',()=>updateMedia(item.id,name.value,seconds.value,check.checked)),mediaButton('↑',()=>orderMedia(item.id,'up')),mediaButton('↓',()=>orderMedia(item.id,'down')),mediaButton('삭제',()=>deleteMedia(item.id,item.name),'danger'));const meta=document.createElement('div');meta.className='media-meta';meta.textContent=`${item.animated?'애니메이션':'사진'} · ${item.frames}프레임 · ${(item.size/1024).toFixed(1)} KiB · ${(item.duration_ms/1000).toFixed(1)}초`;row.append(name,seconds,enabled,actions,meta);box.appendChild(row)}}catch(e){$('media_storage').textContent=e.message;$('media_storage').className='status bad'}}
async function updateMedia(id,name,display,enabled){try{await api('/api/media/update',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:form({id,name,display,enabled:enabled?1:0})});await loadMedia();mediaMessage('미디어 설정을 저장했습니다.')}catch(e){mediaMessage(e.message,true)}}
async function orderMedia(id,direction){try{await api('/api/media/order',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:form({id,direction})});await loadMedia()}catch(e){mediaMessage(e.message,true)}}
async function deleteMedia(id,name){if(!confirm(`“${name}” 미디어를 삭제하시겠습니까?`))return;try{await api('/api/media/delete',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:form({id})});await loadMedia()}catch(e){mediaMessage(e.message,true)}}
async function clearMedia(){if(prompt('전체 미디어를 삭제하려면 MEDIA를 입력하세요.')!=='MEDIA')return;try{await api('/api/media/clear',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:form({confirm:'MEDIA'})});await loadMedia();mediaMessage('커스텀 미디어를 모두 삭제했습니다.')}catch(e){mediaMessage(e.message,true)}}
async function repairMedia(){if(prompt('복구하면 모든 미디어가 삭제됩니다. 계속하려면 REPAIR를 입력하세요.')!=='REPAIR')return;try{await api('/api/media/repair',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:form({confirm:'REPAIR'})});await loadMedia();mediaMessage('미디어 저장소를 새로 초기화했습니다.')}catch(e){mediaMessage(e.message,true)}}
async function load(){try{const s=await api('/api/status');renderStatus(s);const c=await api('/api/config');for(const k of ['title','target','message','mode','cycle_order','cycle_interval','dday_style','after_mode','msg_align','scroll_speed','hour24','show_seconds','ntp_period','dday_period','retry_period','brightness','night_level','led_brightness','led_night_level','screen_off'])if($(k))$(k).value=c[k];syncRangePairs();$('ssid').value=c.wifi_ssid||'';$('wifi_security').value=c.wifi_security||'personal';$('wifi_username').value=c.wifi_username||'';$('wifi_identity').value=c.wifi_identity||'';const enterpriseOption=$('wifi_security').querySelector('option[value="enterprise_peap"]');if(enterpriseOption)enterpriseOption.disabled=c.enterprise_supported===false;syncWifiSecurityUi();$('msg_scroll').checked=!!c.msg_scroll;$('show_temp').checked=!!c.show_temp;$('boot_sync').checked=!!c.boot_sync;$('wifi_sleep').checked=!!c.wifi_sleep;$('burnin').checked=!!c.burnin;$('led_enabled').checked=!!c.led_enabled;$('night_start').value=minsToTime(c.night_start);$('night_end').value=minsToTime(c.night_end);document.querySelectorAll('.cycle').forEach(x=>x.checked=(c.cycle_mask&(1<<Number(x.value)))!==0);renderSavedNetworks(c.saved_networks||[]);await refreshDiagnostics()}catch(e){setStatus(e.message,'bad')}}
function resetInstallConfirm(){installConfirmArmed=false;if(installConfirmTimer){clearTimeout(installConfirmTimer);installConfirmTimer=0}const b=$('install_update');b.classList.remove('install-armed');if(!installRequestPending)b.textContent='업데이트 설치'}
function renderUpdate(s){const latest=s.latest_firmware||'-';const lines=[`현재 버전: ${s.firmware}`,`최신 확인 버전: ${latest}`,`상태: ${s.update_state||'idle'}`,`마지막 확인: ${s.last_update_check||'-'}`];if(s.last_ota_result)lines.push(`최근 설치 결과: ${s.last_ota_result}`);if(s.rollback_armed)lines.push(`롤백 보호: 검증 중 (복귀 ${s.rollback_previous||'이전 슬롯'}, 시도 ${s.rollback_attempt||0})`);else if(s.rollback_last)lines.push(`최근 롤백 상태: ${s.rollback_last}${s.rollback_reason?' — '+s.rollback_reason:''}`);if(s.update_state==='downloading')lines.push(`다운로드: ${s.update_progress||0}%`);if(s.update_error)lines.push(`오류: ${s.update_error}`);$('update_status').textContent=lines.join('\n');$('update_status').className='status '+(s.update_available||s.update_state==='current'?'ok':s.update_error?'bad':'');const b=$('install_update');const transfer=['downloading','verifying','rebooting'].includes(s.update_state);const queued=!!s.update_install_pending;const ready=!!s.update_install_ready;installRequestPending=queued||transfer;if(transfer||queued){resetInstallConfirm();b.disabled=true;b.textContent=transfer?'설치 진행 중…':'설치 요청 처리 중…'}else{b.disabled=!ready;if(!ready)resetInstallConfirm();else if(!installConfirmArmed)b.textContent='업데이트 설치'}}
function renderStatus(s){const mb=n=>(Number(n||0)/1048576).toFixed(2)+' MB';const kb=n=>(Number(n||0)/1024).toFixed(1)+' KB';const up=Number(s.uptime_sec||0);const uptime=`${Math.floor(up/86400)}일 ${String(Math.floor(up/3600)%24).padStart(2,'0')}:${String(Math.floor(up/60)%60).padStart(2,'0')}:${String(up%60).padStart(2,'0')}`;setStatus(`펌웨어: ${s.firmware}\n상태: ${s.state}\n가동 시간: ${uptime}\nCPU: ${s.cpu_mhz||'-'} MHz / 온도: ${s.temperature_c??'-'} °C\nRAM: ${mb(s.heap_free)} 여유 / ${mb(s.heap_total)} 전체\n최저 RAM: ${mb(s.heap_min)} / 최대 연속 블록: ${mb(s.heap_largest)}\n최소 잔여 작업 스택: ${kb(s.stack_free)}\n플래시: ${mb(s.flash_total)} / 앱: ${mb(s.sketch_size)} / OTA 공간: ${mb(s.ota_free)}\nNVS: ${s.nvs_ready?'정상 · 여유 '+s.nvs_free_entries+' entries':'오류'}\nWi-Fi: ${s.wifi}\nIP: ${s.ip||'-'}\n시간: ${s.time_valid?'동기화됨':'미확정'}\n마지막 동기화: ${s.last_sync||'-'}${s.wifi_test&&s.wifi_test!=='idle'?'\nWi-Fi 시험: '+s.wifi_test:''}`,s.nvs_ready===false?'bad':s.time_valid?'ok':'');renderUpdate(s)}
async function refresh(){try{const s=await api('/api/status');renderStatus(s);if(wifiPolling){if(s.wifi_test==='success'){wifiPolling=false;setStatus('Wi-Fi 및 시간 동기화 성공. 설정을 확정 저장했습니다.','ok')}else if(s.wifi_test==='failed'){wifiPolling=false;setStatus('Wi-Fi 시험 실패: '+(s.wifi_error||'연결 또는 시간 동기화 실패'),'bad')}else setTimeout(refresh,1000)}}catch(e){setStatus(e.message,'bad')}}
const wait=ms=>new Promise(resolve=>setTimeout(resolve,ms));
async function scanWifi(){setStatus('주변 2.4GHz Wi-Fi 검색 중…');try{let d;for(let i=0;i<40;i++){d=await api('/api/wifi/scan');if(d.state!=='scanning')break;await wait(300)}if(!d||!Array.isArray(d.networks))throw new Error('Wi-Fi 검색 시간이 초과되었습니다.');const s=$('scan');s.innerHTML='<option value="">검색 결과 선택</option>';d.networks.forEach(n=>{const o=document.createElement('option');o.value=n.ssid;o.dataset.enterprise=n.enterprise?'1':'0';o.dataset.enterpriseCaRequired=n.enterprise_ca_required?'1':'0';o.textContent=`${n.ssid} (${n.rssi} dBm)${n.enterprise_ca_required?' [WPA3 Enterprise · CA 필요]':n.enterprise?' [WPA2 Enterprise]':n.open?' [열림]':''}`;s.appendChild(o)});s.onchange=()=>{if(!s.value)return;const o=s.options[s.selectedIndex];const changed=$('ssid').value!==s.value;$('ssid').value=s.value;if(changed){$('pass').value='';$('wifi_username').value='';$('wifi_identity').value=''}if(o.dataset.enterpriseCaRequired==='1'){$('wifi_security').value='personal';syncWifiSecurityUi();setStatus('이 네트워크는 WPA3-Enterprise/CA 인증이 필요해 현재 버전에서는 지원하지 않습니다.','bad');return}$('wifi_security').value=o.dataset.enterprise==='1'?'enterprise_peap':'personal';syncWifiSecurityUi()};setStatus(`${d.networks.length}개 네트워크 검색 완료`,'ok')}catch(e){setStatus(e.message,'bad')}}
async function testWifi(){if(!val('ssid'))return setStatus('SSID를 입력하세요.','bad');const enterprise=val('wifi_security')==='enterprise_peap';setStatus(enterprise?'AP를 유지한 채 Enterprise Wi-Fi와 NTP를 시험합니다…':'AP를 유지한 채 Wi-Fi와 NTP를 시험합니다…');try{await api('/api/wifi/test',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:form({ssid:val('ssid'),pass:val('pass'),security:val('wifi_security'),username:val('wifi_username'),identity:val('wifi_identity')})});wifiPolling=true;setTimeout(refresh,700)}catch(e){setStatus(e.message,'bad')}}
async function deleteSavedWifi(ssid){if(!confirm(`저장된 Wi-Fi “${ssid}”를 삭제하시겠습니까?`))return;try{await api('/api/wifi/delete',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:form({ssid})});$('pass').value='';await load();setStatus('저장된 Wi-Fi를 삭제했습니다.','ok')}catch(e){setStatus(e.message,'bad')}}
function configBody(){let mask=0;document.querySelectorAll('.cycle:checked').forEach(x=>mask|=1<<Number(x.value));return form({title:val('title'),target:val('target'),message:val('message'),mode:val('mode'),cycle_mask:mask,cycle_order:val('cycle_order'),cycle_interval:val('cycle_interval'),dday_style:val('dday_style'),after_mode:val('after_mode'),msg_align:val('msg_align'),msg_scroll:$('msg_scroll').checked?1:0,scroll_speed:val('scroll_speed'),hour24:val('hour24'),show_seconds:val('show_seconds'),show_temp:$('show_temp').checked?1:0,boot_sync:$('boot_sync').checked?1:0,ntp_period:val('ntp_period'),dday_period:val('dday_period'),retry_period:val('retry_period'),wifi_sleep:$('wifi_sleep').checked?1:0,brightness:val('brightness'),night_level:val('night_level'),led_enabled:$('led_enabled').checked?1:0,led_brightness:val('led_brightness'),led_night_level:val('led_night_level'),night_start:timeToMins(val('night_start')),night_end:timeToMins(val('night_end')),burnin:$('burnin').checked?1:0,screen_off:val('screen_off')})}
async function saveConfig(){setStatus('설정 검증 및 저장 중…');try{await api('/api/config',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:configBody()});setStatus('설정을 저장했습니다.','ok');setTimeout(refresh,500)}catch(e){setStatus(e.message,'bad')}}
async function syncTime(){setStatus('NTP 동기화를 요청했습니다…');try{const d=await api('/api/time/sync',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:form({})});if(d.state==='connecting')setStatus('저장된 Wi-Fi에 다시 연결한 뒤 시간을 동기화합니다…');setTimeout(refresh,1500)}catch(e){setStatus(e.message,'bad')}}
async function checkUpdate(){setStatus('GitHub에서 최신 펌웨어를 확인합니다…');try{await api('/api/update/check',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:form({})});setTimeout(refresh,700)}catch(e){setStatus(e.message,'bad')}}
async function installUpdate(){const b=$('install_update');if(b.disabled)return;if(!installConfirmArmed){installConfirmArmed=true;b.classList.add('install-armed');b.textContent='정말 설치';setStatus('설치하려면 8초 이내에 “정말 설치”를 한 번 더 누르세요. 설치 중에는 전원을 분리하면 안 됩니다.');installConfirmTimer=setTimeout(()=>{resetInstallConfirm()},8000);return}resetInstallConfirm();installRequestPending=true;b.disabled=true;b.textContent='설치 요청 처리 중…';setStatus('펌웨어 설치 요청을 전송합니다…','ok');try{const d=await api('/api/update/install',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:form({})});if(d.state==='reconnecting'){installRequestPending=false;setStatus('저장된 Wi-Fi에 다시 연결하고 최신 정보를 확인합니다. 연결 후 설치 버튼을 다시 눌러 주세요.','ok');setTimeout(refresh,1500)}else{setStatus('설치 요청이 접수되었습니다. 곧 다운로드를 시작하며, 이후 포털 응답이 잠시 멈출 수 있습니다. OLED에서 진행률을 확인해 주세요.','ok');setTimeout(refresh,400)}}catch(e){installRequestPending=false;resetInstallConfirm();setStatus(e.message,'bad');setTimeout(refresh,500)}}
async function exportConfig(){try{const c=await api('/api/config');const e=$('export');e.hidden=false;e.value=JSON.stringify(c,null,2)}catch(e){setStatus(e.message,'bad')}}
async function resetSettings(){if(!confirm('저장된 Wi-Fi는 유지하고 화면·시간·LED 설정을 기본값으로 복원하시겠습니까?'))return;try{await api('/api/settings/reset',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:form({confirm:'DEFAULTS'})});await load();setStatus('표시 설정을 기본값으로 복원했습니다. 저장된 Wi-Fi는 유지됩니다.','ok')}catch(e){setStatus(e.message,'bad')}}
async function factoryReset(){if(prompt('초기화하려면 RESET을 입력하세요.')!=='RESET')return;try{await api('/api/reset',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:form({confirm:'RESET'})});setStatus('초기화 중입니다. 기기가 재부팅됩니다.','ok')}catch(e){setStatus(e.message,'bad')}}
rangePairs.forEach(p=>bindRangePair(...p));mediaCtx.fillRect(0,0,128,128);load();loadMedia();setInterval(()=>{if(!wifiPolling)refresh();refreshDiagnostics()},10000);
</script></body></html>
)HTML";
