#pragma once

// Dedicated lightweight live-stream portal. Kept separate from the full setup
// portal so the browser does not poll diagnostics/config/media APIs while it is
// pacing video frames to the ESP32.
static const char MILESTONE_STREAM_HTML[] PROGMEM = R"HTML(
<!doctype html><html lang="ko"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">
<title>MILESTONE Stream</title>
<style>
:root{color-scheme:dark;--bg:#0b0f10;--card:#141a1c;--line:#263236;--mint:#57efc4;--text:#edf7f4;--muted:#9aaba6;--bad:#ff6b78}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--text);font:15px system-ui,-apple-system,"Noto Sans KR",sans-serif}main{width:min(720px,100%);margin:auto;padding:18px 14px 50px}h1{font-size:23px;margin:4px 0}.brand{color:var(--mint);letter-spacing:.08em}.sub,small{color:var(--muted)}.card{background:var(--card);border:1px solid var(--line);border-radius:14px;padding:15px;margin:12px 0}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.full{grid-column:1/-1}label{display:block;color:var(--muted);font-size:13px;margin-bottom:5px}input,select,button{width:100%;border:1px solid var(--line);border-radius:9px;background:#0d1315;color:var(--text);padding:11px;font:inherit}button{cursor:pointer;background:#1b2828;font-weight:700}button.primary{background:var(--mint);color:#062019;border-color:var(--mint)}button:disabled{opacity:.45;cursor:not-allowed}.row{display:flex;gap:8px}.row>*{flex:1}.check{display:flex;gap:8px;align-items:center;color:var(--text)}.check input{width:auto}.status{white-space:pre-wrap;background:#0a0e0f;border-radius:9px;padding:11px;color:var(--muted);min-height:44px}.ok{color:var(--mint)}.bad{color:var(--bad)}.progress{height:8px;background:#080b0c;border-radius:8px;overflow:hidden}.progress>i{display:block;height:100%;width:0;background:var(--mint)}canvas{width:min(256px,100%);aspect-ratio:1;image-rendering:pixelated;background:#000;border:1px solid var(--line);border-radius:9px}.preview-wrap{display:grid;grid-template-columns:256px minmax(0,1fr);gap:14px}.video-source{position:fixed;left:-8px;top:-8px;width:2px;height:2px;opacity:.01;pointer-events:none}.back{display:inline-block;color:var(--mint);text-decoration:none;margin-top:4px}.metric{font:12px ui-monospace,SFMono-Regular,monospace}.note{border-left:3px solid var(--line);padding-left:10px}@media(max-width:620px){.grid{grid-template-columns:1fr}.preview-wrap{grid-template-columns:1fr}.row{flex-direction:column}}
</style></head><body><main>
<div class="brand">CYTRON//MILESTONE</div><h1>MILESTONE Stream</h1><p class="sub">전체 선변환 후 ESP32 STREAM_MODE로 정속 전송</p><a class="back" href="/">← 일반 설정으로 돌아가기</a>
<section class="card"><div class="preview-wrap"><canvas id="preview" width="128" height="128"></canvas><div class="grid">
<div class="full"><label>로컬 동영상</label><input id="file" type="file" accept="video/*"><small>휴대폰/PC에서 영상 전체를 먼저 128×128 1bit 프레임으로 변환합니다.</small></div>
<div class="full"><label>직접 영상 URL (선택)</label><input id="url" type="url" placeholder="https://example.com/video.mp4"><small>YouTube 페이지 URL은 픽셀을 직접 읽을 수 없으므로 지원하지 않습니다. CORS가 허용된 직접 영상 URL만 사용할 수 있습니다.</small></div>
<div><label>FPS</label><select id="fps"><option value="5">5 fps</option><option value="10">10 fps</option><option value="15">15 fps</option><option value="18">18 fps</option><option value="20" selected>20 fps</option><option value="24">24 fps · Experimental</option></select></div>
<div><label>화면 맞춤</label><select id="fit"><option value="cover">화면 채우기</option><option value="contain">전체 보이기</option></select></div>
<div><label>흑백 변환</label><select id="dither"><option value="bayer">Bayer</option><option value="threshold">임계값</option><option value="floyd">Floyd–Steinberg</option></select></div>
<div><label>밝기 임계값</label><input id="threshold" type="range" min="40" max="220" value="128"></div>
<div><label>밝기 (-100~100)</label><input id="brightness" type="number" min="-100" max="100" value="0"></div>
<div><label>대비 (-100~100)</label><input id="contrast" type="number" min="-100" max="100" value="0"></div>
<div><label>여백</label><select id="background"><option value="black">검은색</option><option value="white">흰색</option></select></div>
<label class="check"><input id="invert" type="checkbox"> 흑백 반전</label>
</div></div></section>
<section class="card"><div class="row"><button id="convert" class="primary" type="button">전체 변환</button><button id="cancel" type="button" disabled>변환 취소</button></div><div class="progress" style="margin-top:10px"><i id="progress"></i></div><div id="convert_status" class="status" style="margin-top:10px">영상 선택 대기</div></section>
<section class="card"><div class="row"><button id="start" class="primary" type="button" disabled>▶ 스트리밍 시작</button><button id="stop" type="button" disabled>■ 중지</button></div><div id="stream_status" class="status metric" style="margin-top:10px">스트리밍 대기</div><p class="note"><small>스트리밍 중 ESP32는 NTP·OTA·일반 화면·저장형 미디어·일반 진단 처리를 쉬고, Wi-Fi 수신·PSRAM 버퍼·OLED·버튼·온도 보호에 집중합니다. 80°C에서 스트리밍을 중단합니다.</small></p></section>
<video id="video" class="video-source" muted playsinline webkit-playsinline preload="metadata"></video>
</main><script>
const $=id=>document.getElementById(id),wait=ms=>new Promise(r=>setTimeout(r,ms));
const FRAME_BYTES=2048,CHUNK_FRAMES=128,INITIAL_FILL_FRAMES=20,LOW_WATERMARK=12,REFILL_TARGET=24,REFILL_FLOOR=22,QUEUE_SAFETY_FRAMES=2,MAX_PUSH_FRAMES=8;
const canvas=$('preview'),ctx=canvas.getContext('2d',{willReadFrequently:true}),work=document.createElement('canvas'),wctx=work.getContext('2d',{willReadFrequently:true});work.width=work.height=128;
const gray=new Float32Array(16384),packed=new Uint8Array(FRAME_BYTES);
let state={converting:false,cancel:false,prepared:false,active:false,stopping:false,objectUrl:'',sourceLabel:'',fps:20,frameCount:0,chunks:[],signature:'',session:0,seq:0,sent:0,lastAck:null,lastAckAt:0,rttMs:0,started:0};
function msg(id,text,bad=false,ok=false){const e=$(id);e.textContent=text;e.className='status'+(bad?' bad':ok?' ok':'')}
function settingsSignature(){return [Number($('fps').value),$('fit').value,$('dither').value,$('threshold').value,$('brightness').value,$('contrast').value,$('background').value,$('invert').checked?1:0].join('|')}
function invalidate(){if(state.converting||state.active)return;state.prepared=false;state.frameCount=0;state.chunks=[];$('start').disabled=true;$('progress').style.width='0%';msg('convert_status','설정이 변경되었습니다. 전체 변환을 다시 실행하세요.')}
function clearStore(){state.frameCount=0;state.chunks=[];state.prepared=false}
function appendFrame(frame){const index=state.frameCount++,ci=Math.floor(index/CHUNK_FRAMES),oi=(index%CHUNK_FRAMES)*FRAME_BYTES;if(!state.chunks[ci])state.chunks[ci]=new Uint8Array(CHUNK_FRAMES*FRAME_BYTES);state.chunks[ci].set(frame,oi)}
function copyFrames(start,count){const out=new Uint8Array(count*FRAME_BYTES);for(let i=0;i<count;i++){const n=start+i,ci=Math.floor(n/CHUNK_FRAMES),oi=(n%CHUNK_FRAMES)*FRAME_BYTES;out.set(state.chunks[ci].subarray(oi,oi+FRAME_BYTES),i*FRAME_BYTES)}return out}
function cleanupSource(){const v=$('video');v.pause();v.removeAttribute('src');try{v.load()}catch{}if(state.objectUrl){URL.revokeObjectURL(state.objectUrl);state.objectUrl=''}}
function waitForVideo(video,events,timeout,message){return new Promise((resolve,reject)=>{let timer=0;const done=()=>{clean();resolve()},fail=()=>{clean();reject(new Error(message))},clean=()=>{if(timer)clearTimeout(timer);for(const event of events)video.removeEventListener(event,done);video.removeEventListener('error',fail)};for(const event of events)video.addEventListener(event,done,{once:true});video.addEventListener('error',fail,{once:true});timer=setTimeout(fail,timeout)})}
async function openSource(){cleanupSource();const video=$('video'),file=$('file').files&&$('file').files[0],url=$('url').value.trim();video.muted=true;video.defaultMuted=true;video.playsInline=true;let src='';if(file){src=URL.createObjectURL(file);state.objectUrl=src;state.sourceLabel=file.name}else if(url){let host='';try{host=new URL(url).hostname}catch{}if(/(^|\.)youtu\.be$|(^|\.)youtube\.com$|(^|\.)youtube-nocookie\.com$/i.test(host))throw new Error('YouTube 페이지 URL은 직접 프레임 변환할 수 없습니다. 로컬 영상 또는 직접 영상 URL을 사용하세요.');video.crossOrigin='anonymous';src=url;state.sourceLabel=url}else throw new Error('동영상을 선택하세요.');const p=waitForVideo(video,['loadedmetadata'],45000,'영상 정보를 읽지 못했습니다. 원본 다운로드 상태를 확인하세요.');video.src=src;video.load();await p;if(!Number.isFinite(video.duration)||video.duration<=0||!video.videoWidth||!video.videoHeight)throw new Error('영상 길이 또는 해상도를 읽지 못했습니다.');return video}
async function seek(video,time){const target=Math.max(0,Math.min(Math.max(0,video.duration-.02),time));if(Math.abs(video.currentTime-target)<.002&&video.readyState>=2)return;const ready=waitForVideo(video,['seeked','loadeddata'],12000,'영상 프레임을 읽는 시간이 초과되었습니다.');video.currentTime=target;await ready;if(video.readyState<2)await waitForVideo(video,['loadeddata','canplay'],5000,'영상 프레임을 디코딩하지 못했습니다.')}
function drawFrame(source,w,h){wctx.save();wctx.setTransform(1,0,0,1,0,0);wctx.fillStyle=$('background').value==='white'?'#fff':'#000';wctx.fillRect(0,0,128,128);const scale=$('fit').value==='contain'?Math.min(128/w,128/h):Math.max(128/w,128/h),dw=w*scale,dh=h*scale;wctx.imageSmoothingEnabled=true;wctx.imageSmoothingQuality='high';wctx.drawImage(source,(128-dw)/2,(128-dh)/2,dw,dh);wctx.restore();ctx.setTransform(1,0,0,1,0,0);ctx.drawImage(work,0,0)}
function packFrame(){const p=wctx.getImageData(0,0,128,128).data,threshold=Number($('threshold').value),brightness=Math.max(-100,Math.min(100,Number($('brightness').value)||0))*2.55,contrast=Math.max(-100,Math.min(100,Number($('contrast').value)||0)),factor=(259*(contrast+255))/(255*(259-contrast)),invert=$('invert').checked,bayer=[0,8,2,10,12,4,14,6,3,11,1,9,15,7,13,5],mode=$('dither').value;packed.fill(0);for(let i=0;i<16384;i++){const o=i*4,a=p[o+3]/255;let lum=(.2126*p[o]+.7152*p[o+1]+.0722*p[o+2])*a;lum=Math.max(0,Math.min(255,factor*(lum-128)+128+brightness));gray[i]=invert?255-lum:lum}for(let y=0;y<128;y++)for(let x=0;x<128;x++){const i=y*128+x,t=threshold+(mode==='bayer'?(bayer[(y&3)*4+(x&3)]-7.5)*8:0),on=gray[i]>=t;if(on)packed[x+(y>>3)*128]|=1<<(y&7);if(mode==='floyd'){const e=gray[i]-(on?255:0);if(x<127)gray[i+1]+=e*7/16;if(y<127){if(x)gray[i+127]+=e*3/16;gray[i+128]+=e*5/16;if(x<127)gray[i+129]+=e/16}}}return packed}
async function convertAll(){if(state.converting||state.active)return;state.converting=true;state.cancel=false;clearStore();$('convert').disabled=true;$('cancel').disabled=false;$('start').disabled=true;msg('convert_status','영상 정보를 준비하는 중…');let video;try{video=await openSource();const fps=Math.max(5,Math.min(24,Number($('fps').value)||20)),count=Math.max(1,Math.ceil(video.duration*fps)),estimate=count*FRAME_BYTES;state.fps=fps;state.signature=settingsSignature();const started=performance.now();for(let i=0;i<count;i++){if(state.cancel)throw new Error('변환을 취소했습니다.');await seek(video,i/fps);drawFrame(video,video.videoWidth,video.videoHeight);appendFrame(packFrame());if((i&3)===0||i+1===count){const pct=Math.round((i+1)*100/count);$('progress').style.width=pct+'%';msg('convert_status',`전체 선변환 중 ${i+1}/${count} · ${pct}%\n예상 RAW ${(estimate/1048576).toFixed(1)} MiB · 경과 ${((performance.now()-started)/1000).toFixed(1)}초`);await wait(0)}}state.prepared=true;$('start').disabled=false;msg('convert_status',`변환 완료 · ${state.frameCount}프레임 · ${fps}fps · ${(state.frameCount*FRAME_BYTES/1048576).toFixed(1)} MiB\n스트리밍 중에는 영상 디코딩을 다시 하지 않습니다.`,false,true)}catch(e){clearStore();msg('convert_status',e.message,true)}finally{cleanupSource();state.converting=false;$('convert').disabled=false;$('cancel').disabled=true}}
async function apiJson(url,opt={}){const r=await fetch(url,opt),t=await r.text();let d;try{d=JSON.parse(t)}catch{d={error:t||r.statusText}}if(!r.ok)throw new Error(d.error||`HTTP ${r.status}`);return d}
function parseAck(buffer){if(buffer.byteLength!==28)throw new Error(`스트림 ACK 길이 오류: ${buffer.byteLength}`);const v=new DataView(buffer);if(v.getUint8(0)!==77||v.getUint8(1)!==83||v.getUint8(2)!==65||v.getUint8(3)!==49)throw new Error('스트림 ACK 형식 오류');return{version:v.getUint8(4),phase:v.getUint8(5),queue:v.getUint8(6),capacity:v.getUint8(7),received:v.getUint32(8,true),displayed:v.getUint32(12,true),dropped:v.getUint32(16,true),underruns:v.getUint16(20,true),temp:v.getInt16(22,true)/10,actualFps:v.getUint16(24,true)/10,flushUs:v.getUint16(26,true)*10}}
function showAck(a){const elapsed=Math.max(.001,(performance.now()-state.started)/1000),sendFps=state.sent/elapsed;msg('stream_status',`STREAM_MODE · ${a.phase===1?'BUFFERING':a.phase===2?'PLAYING':'ACTIVE'}\n목표 ${state.fps} fps · 실제 ${a.actualFps.toFixed(1)} fps · 송신 ${sendFps.toFixed(1)} fps\n버퍼 ${a.queue}/${a.capacity} · 송신 ${state.sent}/${state.frameCount}\n기기 수신 ${a.received} · 표시 ${a.displayed} · 드롭 ${a.dropped} · 언더런 ${a.underruns}\nOLED flush ${(a.flushUs/1000).toFixed(1)} ms · HTTP RTT ${state.rttMs.toFixed(0)} ms · 온도 ${a.temp.toFixed(1)}°C`,false,true)}
async function pushRaw(start,count){const body=copyFrames(start,count),seq=++state.seq,url='/api/stream/push',headers={'Content-Type':'application/octet-stream','X-MILESTONE-Session':String(state.session),'X-MILESTONE-Seq':String(seq),'X-MILESTONE-Count':String(count)};let lastError=null;for(let attempt=0;attempt<30&&state.active;attempt++){const attemptStarted=performance.now();let r;try{r=await fetch(url,{method:'POST',headers,body})}catch(e){lastError=e;if(attempt+1<30&&state.active){await wait(Math.max(25,Math.round(500/state.fps)));continue}break}if(r.ok){try{const a=parseAck(await r.arrayBuffer()),receivedAt=performance.now(),sampleRtt=Math.max(0,receivedAt-attemptStarted);state.rttMs=state.rttMs?state.rttMs*.75+sampleRtt*.25:sampleRtt;state.lastAck=a;state.lastAckAt=receivedAt;state.sent+=count;showAck(a);return a}catch(e){lastError=e;if(attempt+1<30&&state.active){await wait(Math.max(25,Math.round(500/state.fps)));continue}break}}let text='';try{text=await r.text()}catch(e){lastError=e;if(attempt+1<30&&state.active){await wait(Math.max(25,Math.round(500/state.fps)));continue}break}if(r.status===409&&/buffer-full/.test(text)){await wait(Math.max(20,Math.round(500/state.fps)));continue}throw new Error(text||`HTTP ${r.status}`)}throw lastError||new Error('ESP32 스트림 전송을 재시도했지만 응답을 받지 못했습니다.')}
function estimatedQueue(){if(!state.lastAck)return 0;let q=Math.max(0,state.lastAck.queue-QUEUE_SAFETY_FRAMES);if(state.lastAck.phase===2&&state.lastAckAt>0){const seconds=Math.max(0,(performance.now()-state.lastAckAt)/1000);q=Math.max(0,q-Math.floor(seconds*state.fps))}return q}
async function finishAndDrain(){await apiJson('/api/stream/finish',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({session:state.session})});msg('stream_status','모든 프레임 전송 완료 · ESP32 버퍼 출력 대기 중…',false,true);while(state.active){await wait(250);const d=await apiJson('/api/stream/status');if(!d.active){state.active=false;state.session=0;$('stop').disabled=true;$('start').disabled=!state.prepared;msg('stream_status',`재생 완료 · STREAM_MODE 종료\n표시 ${d.displayed} · 드롭 ${d.dropped} · 언더런 ${d.underruns}`,false,true);return}}}
async function sendLoop(){try{let index=0;const initialTarget=Math.min(INITIAL_FILL_FRAMES,state.frameCount);while(state.active&&index<initialTarget){const count=Math.min(MAX_PUSH_FRAMES,initialTarget-index);await pushRaw(index,count);index+=count}while(state.active&&index<state.frameCount){let queue=estimatedQueue();if(queue>LOW_WATERMARK){const framesAbove=queue-LOW_WATERMARK,delay=Math.max(12,Math.min(150,Math.round(framesAbove*500/state.fps)));await wait(delay);continue}while(state.active&&index<state.frameCount){queue=estimatedQueue();if(queue>=REFILL_FLOOR)break;const capacity=state.lastAck&&state.lastAck.capacity?state.lastAck.capacity:32,target=Math.min(REFILL_TARGET,Math.max(1,capacity-4)),desired=Math.max(1,target-queue),count=Math.min(MAX_PUSH_FRAMES,desired,state.frameCount-index);await pushRaw(index,count);index+=count}if(state.active&&index<state.frameCount&&estimatedQueue()>=REFILL_FLOOR)await wait(12)}if(state.active)await finishAndDrain()}catch(e){if(state.active){msg('stream_status',`스트리밍 중단 · ${e.message}`,true);await stopStream(false,true)}}}
async function startStream(){if(state.active||!state.prepared)return;if(state.signature!==settingsSignature())return invalidate();$('start').disabled=true;try{const d=await apiJson('/api/stream/start',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({fps:state.fps})});state.active=true;state.stopping=false;state.session=Number(d.session);state.seq=0;state.sent=0;state.lastAck=null;state.lastAckAt=0;state.rttMs=0;state.started=performance.now();$('stop').disabled=false;msg('stream_status','STREAM_MODE 진입 · 초기 프레임 선버퍼링 중…',false,true);sendLoop()}catch(e){$('start').disabled=false;msg('stream_status',e.message,true)}}
async function stopStream(ended=false,silent=false){if(state.stopping)return;state.stopping=true;const active=state.active;state.active=false;$('stop').disabled=true;try{if(active)await apiJson('/api/stream/stop',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({session:state.session})})}catch(e){if(!silent)msg('stream_status',`중지 요청 실패 · ${e.message}`,true)}finally{state.session=0;state.stopping=false;$('start').disabled=!state.prepared;if(!silent)msg('stream_status',ended?'재생 완료 · STREAM_MODE 종료':'STREAM_MODE 종료',false,true)}}
$('convert').addEventListener('click',convertAll);$('cancel').addEventListener('click',()=>state.cancel=true);$('start').addEventListener('click',startStream);$('stop').addEventListener('click',()=>stopStream(false));$('file').addEventListener('change',()=>{if($('file').files&&$('file').files[0])$('url').value='';invalidate()});$('url').addEventListener('input',()=>{if($('url').value.trim())$('file').value='';invalidate()});for(const id of ['fps','fit','dither','threshold','brightness','contrast','background','invert'])$(id).addEventListener('change',invalidate);window.addEventListener('pagehide',()=>{if(state.active)fetch('/api/stream/stop',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({session:state.session}),keepalive:true}).catch(()=>{})});
</script></body></html>
)HTML";
