'use strict';
const assert=require('assert'),fs=require('fs'),vm=require('vm');
const source=fs.readFileSync(process.argv[2],'utf8');
const match=source.match(/<script>([\s\S]*?)<\/script>/);assert(match,'stream page script missing');
class El{constructor(id=''){this.id=id;this.value='';this.files=[];this.checked=false;this.disabled=false;this.textContent='';this.className='';this.style={};this.listeners={};}addEventListener(t,f){(this.listeners[t]??=[]).push(f)}removeEventListener(){}getContext(){return{save(){},restore(){},setTransform(){},fillRect(){},drawImage(){},getImageData(){return{data:new Uint8ClampedArray(65536)}}}}pause(){}removeAttribute(){}load(){}}
const els=new Map();for(const id of source.matchAll(/id="([^"]+)"/g))els.set(id[1],new El(id[1]));const get=id=>els.get(id)||(()=>{const e=new El(id);els.set(id,e);return e})();
get('fps').value='20';get('fit').value='cover';get('dither').value='bayer';get('threshold').value='128';get('brightness').value='0';get('contrast').value='0';get('background').value='black';
let lastFetch=null,fetchCalls=[],failFetchCount=0;
function ackBuffer(){const b=new ArrayBuffer(28),v=new DataView(b);[77,83,65,49,1,2,6,240].forEach((x,i)=>v.setUint8(i,x));v.setUint32(8,2,true);v.setUint32(12,1,true);v.setUint32(16,0,true);v.setUint16(20,0,true);v.setInt16(22,715,true);v.setUint16(24,198,true);v.setUint16(26,4100,true);return b;}
const context=vm.createContext({console,Blob,Uint8Array,Uint8ClampedArray,Float32Array,DataView,ArrayBuffer,URLSearchParams,AbortController,Date,Math,Promise,performance:{now:()=>1000},document:{getElementById:get,createElement:()=>new El()},window:{addEventListener(){}},URL:{createObjectURL(){return'blob:x'},revokeObjectURL(){}},setTimeout,clearTimeout,fetch:async(url,opt={})=>{lastFetch={url:String(url),opt};fetchCalls.push(lastFetch);if(failFetchCount>0){failFetchCount--;throw new TypeError('simulated transport loss')}return{ok:true,status:200,statusText:'OK',async arrayBuffer(){return ackBuffer()},async text(){return'{}'}}}});
vm.runInContext(match[1],context,{filename:'StreamPage.inline.js'});
const run=x=>vm.runInContext(x,context);
for(let n=0;n<130;n++)run(`appendFrame(new Uint8Array(2048).fill(${n&255}))`);
assert.strictEqual(run('state.frameCount'),130);
assert.strictEqual(run('deltaRle(frameView(5),frameView(5)).length'),16,'unchanged 2 KiB frame should collapse to sixteen zero-run control bytes');
const firstRecord=run('encodeBatch(0,1)');assert.strictEqual(firstRecord.length,2053);assert.strictEqual(firstRecord[0],0,'first live frame must be RAW');assert.strictEqual(new DataView(firstRecord.buffer).getUint16(3,true),2048);
run('appendFrame(new Uint8Array(2048).fill(129))');
const deltaRecord=run('encodeBatch(130,1)');assert.strictEqual(deltaRecord.length,21,'unchanged live frame should use a 5-byte record header plus 16-byte XOR-RLE payload');assert.strictEqual(deltaRecord[0],1,'smaller follow-up frame must use XOR-RLE');assert.strictEqual(new DataView(deltaRecord.buffer).getUint16(1,true),0);assert.strictEqual(new DataView(deltaRecord.buffer).getUint16(3,true),16);for(let i=5;i<deltaRecord.length;i++)assert.strictEqual(deltaRecord[i],127,'unchanged frame must encode as sixteen 128-byte zero runs');
const crossed=run('copyFrames(127,3)');assert.strictEqual(crossed.length,6144);assert.strictEqual(crossed[0],127);assert.strictEqual(crossed[2048],128);assert.strictEqual(crossed[4096],129);
const parsed=run('parseAck((()=>{const b=new ArrayBuffer(28),v=new DataView(b);[77,83,65,49,1,2,6,240].forEach((x,i)=>v.setUint8(i,x));v.setUint32(8,12,true);v.setUint32(12,10,true);v.setUint32(16,2,true);v.setUint16(20,1,true);v.setInt16(22,755,true);v.setUint16(24,203,true);v.setUint16(26,3200,true);return b})())');
assert.strictEqual(parsed.queue,6);assert.strictEqual(parsed.capacity,240);assert.strictEqual(parsed.temp,75.5);assert.strictEqual(parsed.actualFps,20.3);
assert(/INITIAL_FILL_FRAMES=96/.test(source));assert(/LOW_WATERMARK=64/.test(source));assert(/REFILL_TARGET=176/.test(source));assert(/REFILL_FLOOR=144/.test(source));assert(/QUEUE_SAFETY_FRAMES=4/.test(source));assert(/MAX_PUSH_FRAMES=24/.test(source));assert(/PUSH_TIMEOUT_MS=5000/.test(source));assert(!/LEAD_FRAMES|STEADY_PUSH_FRAMES/.test(source));
run('state.fps=20;state.lastAck={queue:96,phase:2,actualFps:5};state.lastAckAt=500');assert.strictEqual(run('estimatedQueue()'),94,'queue estimate must use measured device drain instead of the requested source FPS');
run('state.active=true;state.session=1234;state.seq=0;state.sent=0;state.started=500;state.frameCount=130');
run('pushRaw(0,2)').then(async()=>{assert.strictEqual(lastFetch.url,'/api/stream/push');assert.strictEqual(lastFetch.opt.headers['Content-Type'],'application/octet-stream');assert.strictEqual(lastFetch.opt.headers['X-MILESTONE-Session'],'1234');assert.strictEqual(lastFetch.opt.headers['X-MILESTONE-Seq'],'1');assert.strictEqual(lastFetch.opt.headers['X-MILESTONE-Count'],'2');assert.strictEqual(lastFetch.opt.headers['X-MILESTONE-Bytes'],'4106');assert.strictEqual(lastFetch.opt.body.byteLength,4106);assert(lastFetch.opt.signal instanceof AbortSignal,'stream push needs a bounded fetch timeout');fetchCalls=[];failFetchCount=1;await run('pushRaw(2,2)');assert.strictEqual(fetchCalls.length,2,'transport loss should retry exactly the same batch');assert.strictEqual(fetchCalls[0].url,fetchCalls[1].url);assert.strictEqual(fetchCalls[0].url,'/api/stream/push');assert.strictEqual(fetchCalls[0].opt.headers,fetchCalls[1].opt.headers,'retry must reuse the same stream metadata headers object');assert.strictEqual(fetchCalls[0].opt.headers['X-MILESTONE-Seq'],'2');assert.strictEqual(fetchCalls[0].opt.headers['X-MILESTONE-Count'],'2');assert.strictEqual(fetchCalls[0].opt.headers['X-MILESTONE-Bytes'],String(fetchCalls[0].opt.body.byteLength));assert.strictEqual(fetchCalls[0].opt.body,fetchCalls[1].opt.body,'retry must reuse the same binary body');assert.strictEqual(run('state.seq'),2,'retry must not consume a new sequence number');console.log('Dedicated stream page state-machine test passed')}).catch(e=>{console.error(e);process.exitCode=1});
